### ISSUE TITLE
Add support for picklistId field type

### ISSUE THREAD

**Issue by StanislawSwierc** [stansw/vsts-open-in-powerbi#13]
Query can fail with the following error:
```
The field 'piclistId' of the record wasn't found.
```

**Comment by mariusstrom** [comment]
Literally came here to post this after making sure the VSTS repo I was querying is using version 2.0.3 of your extension. :)

**Comment by stansw** [comment]
I followed up offline with people who run into this problem. It was fixed 25 days ago. I'm closing this issue.
