### ISSUE TITLE
Issue using this extenstion for VSO Flat query type 

### ISSUE THREAD

**Issue by gchawla-msft** [stansw/vsts-open-in-powerbi#14]
Hi, 
When i am try to open a flat query in Power BI I am getting the below error. The extension is working fine for Tree view or Related linked query type.
<img width="479" alt="flatqueryerror" src="https://user-images.githubusercontent.com/39833334/40845501-6555fc02-65a6-11e8-99d6-a9e8f685a075.png">

In the advance editor i get the below error where the activity ID gets updates on every refresh 

<img width="486" alt="flatqueryerror2" src="https://user-images.githubusercontent.com/39833334/40845583-b214113c-65a6-11e8-93bf-0285d24c66d1.png">

Please help me urgently as i have created 10-15 reports shared to my management leads  using this extension and is failing to refresh.

**Comment by StanislawSwierc** [comment]
I'm afraid there is not enough information for me to know what's wrong here. Lets schedule a call on Skype to investigate it. My handle is *proxon.pl*. Feel free to reach out.

**Comment by stansw** [comment]
I fixed it! :)

The problem was with the long URL which exceeded 3000 characters supported by the VSTS. I updated the code to fallback to shorter, slower URL.
