### ISSUE TITLE
The import VSTS.Contents matches no exports (Power BI Desktop 2.41.4581.361)

### ISSUE THREAD

**Issue by StanislawSwierc** [stansw/vsts-open-in-powerbi#2]
One customer complained about error he got in Power BI Desktop version 2.41.4581.361.

>The import VSTS.Contents matches no exports

After initial investigation I discovered that this version does not have the "VSTS" extension which was released in January 2017 (https://www.visualstudio.com/en-us/docs/report/powerbi/overview). I will look into how I can detect the version and provide better error message.

**Comment by stansw** [comment]
I've just added information about the min supported version of the Power BI Desktop.

> This extension requires Microsoft Power BI Desktop October 2017 (or later) to be installed locally to open template files (*.pbit).

4119ce3e60af8d299888e1f47ae373d2048b6e2b
