### ISSUE TITLE
Receiving error when opening Query in PowerBI

### ISSUE THREAD

**Issue by llgriff** [stansw/vsts-open-in-powerbi#4]
When I open a query that contains any text picklist column, I receive the error of:

"An error occurred in the ‘Functions’ query. Expression.Error: The field 'picklistString' of the record wasn't found.
Details:
    boolean=Type
    dateTime=Type
    double=Type
    history=Type
    html=Type
    integer=Type
    plainText=Type
    string=Type
    treePath=Type"

Is this expected behavior or an issue with the construction of my query? The data appears to display validly within VSTS.

**Comment by stansw** [comment]
Thank you for reporting that @llgriff, it is a real problem. I've just confirmed that extension does not support several field types. I will add them in the next release.

    string,
    integer,
    dateTime,
    plainText,
    html,
    treePath,
    history,
    double,
    guid,
    boolean,
    identity,
    picklistString,
    picklistInteger,
    picklistDouble

**Comment by stansw** [comment]
This has been fixed.

https://github.com/stansw/vsts-open-in-powerbi/commit/75cf7d023e02ec026695f2462ce197a828b148af
